apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-toolbox
  name: my-toolbox
  namespace: default
spec:
  containers:
  - image: mogaal/toolbox
    imagePullPolicy: Always
    name: my-toolbox
    tty: true
